#server:
  #port: 8878
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zyq002/my.config.git
          username: zyq002
          password: nijie119504
  application:
    name: config-server
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.169.128:8080/my.demo/eureka/
management:
  security:
    enabled: false